<a href="https://colab.research.google.com/github/YamanL/AI-and-its-Application/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [ ]:
#importing numpy library
import numpy as np

#creating a lis named "my_list"
my_list = [1,3,5,7,9]

#creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)
#printing the array
print(my_arr)

#Creating a 0-D array
arr_0d = np.array(42)
#printing the array
print(arr_0d)

#Creating a 2-D array
arr_2d = np.array([[1,2,3],[4,5,6]])
#printing the array
print(arr_2d)

#Creating a 3-D array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#printing the array
print(arr_3d)

[1 3 5 7 9]
42
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##Creating Array and its attributes

In [ ]:
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr) #printing the array
print(arr.ndim) #Dimensions.....
print(arr.shape) #printing the shape of an array
print(arr.size) #Size....
print(arr.dtype) #Type....

[[1 2 3 4]
 [6 7 8 9]]
2
(2, 4)
8
int64


#ACCESSING AND MANIPULATING ARRAY ELEMENTS

In [ ]:
#Accessing 1-D array elements
my_arr = np.array([2,5,7,9])
print(may_arr[2])

7


In [ ]:
#Accessing 2-D array elements
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,2])

5


In [ ]:
#Accessing 3-D array elements
my_arr = np.array([[[2,5,7,9],[1,3,5,7],[2,5,7,9], [1,3,5,7]]])
print(my_arr[0,1,2])

5


#NEGATIVE INDEXING

In [ ]:
#Accessing 2-D array elements with negative indexing
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,-2])


5


a

#SLICING ARRAYS

In [ ]:
arr = np.array([1,3,5,7,9,11,13,15,17,19,21])
print(arr[1:5])  #Slicing
print(arr[1:5:2]) #Slicing with step
print(arr[0:-1]) #Negative

[3 5 7 9]
[3 7]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# SLicing a 2-D numpy array
arr = np.array([[1,3,5,7],[2,4,6,8]])
print (arr[1,1:-1])

CLASSWORK:

Create a NumPy array from the list [7,14,21,28]. Print the array.

In [ ]:
#NumPy array from the list
arr = np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


Create a 2D NumPy array [[5,10,15], [20,25,30]]. Print its shape and muber of dimensions using array.ndim.

In [ ]:
#2-D NumPy array
arr = np.array([[5,10,15],[20,25,30]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[ 5 10 15]
 [20 25 30]]
(2, 3)
2


Use np.zeros to create a 2D array of shape (2,3). Then, use np.arange to create an array from 0 to 12 with a step of 3. Print both arrays.

In [ ]:
a = np.zeros((2, 3))
b = np.arange(0,13,3)

print(a)
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  3  6  9 12]


Create a Numpy array [2,4,6,8]. Multiply all elements by 3 and print the result

In [ ]:
arr = np.array([2,4,6,8])
print(arr*3)

[ 6 12 18 24]


Create a NumPy array [1,3,5,7,9,11]. Print the third element and a slice from index 1 to 3 (inclusive).

In [ ]:
arr = np.array([1,3,5,7,9,11])
print(arr[2])
print(arr[1:4])

5
[3 5 7]


HOMEWORK: EXPERIMENT WITH SLICING ON A 3-D ARRAY

In [ ]:
# prompt: SLICING ON A 3-D ARRAY

import numpy as np
# SLicing a 3-D numpy array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, :])  # Slice the second row of the first "plate"
print(arr[:, :, 1])  # Slice the second column across all rows and "plates"
print(arr[1, :, 0])  # Slice the first element of each row in the second "plate"
print(arr[0, 0:2, 0:2]) # Slice a sub-array from the first "plate"

CLASSWORK
1. Create a 2D NumPy array of shape (3,3) with random integers between 1 and 10 (inclusive) using np.random.randint. Then, replace all values greater than 5 with 0 and print the modified array.


In [ ]:
arr = np.random.randint(1,11,(3,3))
print(arr)
arr[arr>5] = 0
print(arr)

[[ 3  2  9]
 [10  5  2]
 [ 8  4  2]]
[[3 2 0]
 [0 5 2]
 [0 4 2]]


2.Create two 1D NumPy arrays: [2, 4, 6, 8] and [1, 3, 5, 7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.

In [ ]:
import numpy as np

arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([1, 3, 5, 7])

# Element-wise sum
element_wise_sum = arr1 + arr2
print("Element-wise sum:", element_wise_sum)

# Dot product
dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)


Element-wise sum: [ 3  7 11 15]
Dot product: 100


3. Create a 2D NumPy array of shape (4, 3) filled with ones using np.ones. Then, add a 1D array [10, 20, 30] to each row of the 2D array using broadcasting. Print the resulting array.

In [ ]:
import numpy as np
array_2d = np.ones((4, 3))
array_1d = np.array([10, 20, 30])

result_array = array_2d + array_1d
result_array

array([[11., 21., 31.],
       [11., 21., 31.],
       [11., 21., 31.],
       [11., 21., 31.]])

4. Create a 2D NumPy array [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Extract the second column and compute its mean using np. mean. Then, reshape the original array into a 1D array and print both results.

In [4]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the second column (index 1)
second_column = arr[:, 1]

# Compute the mean of the second column
mean_second_column = np.mean(second_column)
print("Mean of the second column:", mean_second_column)

# Reshape the original array into a 1D array
reshaped_array = arr.reshape(-1)
print("Reshaped 1D array:", reshaped_array)

Mean of the second column: 5.0
Reshaped 1D array: [1 2 3 4 5 6 7 8 9]


5. Create a 1D NumPy array [10, 20, 30, 40, 50, 60]. Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.

In [5]:
import numpy as np
# Create the original 1D array
original_array = np.array([10, 20, 30, 40, 50, 60])
print("Original array:", original_array)

# Create a boolean mask for elements greater than 30
mask = original_array > 30

# Select elements greater than 30 using the boolean mask and square them
modified_array = original_array[mask] ** 2
print("Modified array (elements > 30 squared):", modified_array)

Original array: [10 20 30 40 50 60]
Modified array (elements > 30 squared): [1600 2500 3600]
